imports:
- path: vm/content-server-template.jinja
- path: storage/bucket-template.jinja
- path: storage/sql-server-template.jinja
- path: network/network-template.jinja
- path: network/subnetwork-template.jinja
- path: network/firewall-http-template.jinja
- path: network/firewall-ssh-template.jinja
- path: network/VPN/address-template.jinja
- path: network/VPN/gateway-template.jinja
- path: network/VPN/forwarding-rule-template.jinja


resources:
- name: west-eu-content # Will serve UK and EU
  type: vm/content-server-template.jinja
  properties:
    zone: europe-west2-c

- name: content-bucket
  type: storage/bucket-template.jinja

- name: sql-server
  type: storage/sql-server-template.jinja  ## THE SCHEMA FILE FOR THIS BITCH IS ACTIN UP ----- FIX!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  properties:
    region: europe-west2-c
    tier: db-custom-16-61440     ## Ideally, this would scale

- name: custom-network
  type: network/network-template.jinja
  properties:
    autoCreateSubnetworks: false

- name: custom-subnetwork
  type: network/subnetwork-template.jinja
  properties:
    ipCidrRange: 10.10.10.0/24
    network: $(ref.custom-network.selfLink)
    region: europe-west2-c

- name: http-firewall
  type: network/firewall-http-template.jinja
  properties:
    network: $(ref.custom-network.selfLink)
    IPProtocol: TCP

- name: shh-firewall
  type: network/firewall-ssh-template.jinja
  properties:
    network: $(ref.custom-network.selfLink)
    IPProtocol: TCP

- name: static-address
  type: network/VPN/address-template.jinja
  properties:
    region: europe-west2-c

- name: gateway
  type: network/VPN/gateway-template.jinja
  properties:
    region: europe-west2-c
    network: $(ref.custom-network.selfLink)

## ESP forwarding rule
- name: forwarding-rule-esp
  type: network/VPN/forwarding-rule-template.jinja
  properties:
    name: forwarding-rule-esp
    region: europe-west2-c
    IPProtocol: ESP
    IPAddress: $(ref.static-address.address)
    network: $(ref.custom-network.selfLink)
    target: $(ref.gateway.selfLink)

## UDP 500 forwarding rule
- name: forwarding-rule-udp500
  type: network/VPN/forwarding-rule-template.jinja
  properties:
    name: forwarding-rule-udp500
    region: europe-west2-c
    IPProtocol: UDP
    IPAddress: $(ref.static-address.address)
    network: $(ref.custom-network.selfLink)
    target: $(ref.gateway.selfLink)

## UDP 4500 forwarding rule
- name: forwarding-rule-udp4500
  type: network/VPN/forwarding-rule-template.jinja
  properties:
    name: forwarding-rule-udp4500
    region: europe-west2-c
    IPProtocol: UDP
    IPAddress: $(ref.static-address.address)
    network: $(ref.custom-network.selfLink)
    target: $(ref.gateway.selfLink)


## Converge both firewall templates into single template by adding more properties
## SQL SERVER SCHEMA FILE IS ACTING UP

## open port on bucket to HTTP traffic in the firewall rules as well, otherwise nothing can be served lmao.
## Put the bucket on the same network as well?
## Link content server and disk storage as well O.O

## oh, and add an SQL server <3 may have to configure it with the firewall as well idk
## look at scaling the SQL server tier