imports:
- path: vm/content-server-template.jinja
- path: storage/bucket-template.jinja
- path: network/network-template.jinja
- path: network/subnetwork-template.jinja
- path: network/firewall-template.jinja


resources:
- name: west-eu-content # Will serve UK and EU
  type: vm/content-server-template.jinja
  properties:
    zone: europe-west2-c

- name: content-bucket
  type: storage/bucket-template.jinja

- name: custom-network
  type: network/network-template.jinja
  properties:
    autoCreateSubnetworks: false

- name: custom-subnetwork
  type: network/subnetwork-template.jinja
  properties:
    ipCidrRange: 10.10.10.0/24
    network: $(ref.custom-network.selfLink)
    region: europe-west2-c

- name: custom-firewall
  type: network/firewall-template.jinja
  properties:
    network: $(ref.custom-network.selfLink)
    IPProtocol: TCP


## add firewall and CONFIGURE IT!!! Important step lmao 
## firewall added, as well as tags. P sure it's fully configured but maybe deploy and check.

## open port on bucket to HTTP traffic in the firewall rules as well, otherwise nothing can be served lmao.
## Put the bucket on the same network as well?

## oh, and add an SQL server <3 may have to configure it with the firewall as well idk